[project]
name = "lab-tool-usage"
version = "0.1.0"
description = "A script for processing market share data"
authors = [
    {name = "Giuseppe"}
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.31.0,<3.0.0",
    "lxml>=4.9.3,<5.0.0",
    "flashtext>=2.7,<3.0.0",
    "plotly>=5.0.0,<6.0.0",
    "python-dotenv>=1.0,<2.0",
    "yfinance>=0.2,<1.0",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
