import json
import pandas as pd


def create_registry():
    registry_data = [
        # --- GENOMICS & SEQUENCING ---
        {
            "canonical_name": "NovaSeq X / 6000",
            "vendor": "Illumina",
            "parent_company": "Illumina",
            "ticker": "ILMN",
            "category": "NGS Sequencing",
            "gliner_label": "dna sequencer",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "novaseq",
                "illumina novaseq",
                "novaseq x",
                "novaseq 6000",
                "hiseq",
                "solexa",
                "illumina short-read",
            ],
        },
        {
            "canonical_name": "Revio / Sequel IIe",
            "vendor": "Pacific Biosciences",
            "parent_company": "Pacific Biosciences",
            "ticker": "PACB",
            "category": "Long-Read Sequencing",
            "gliner_label": "dna sequencer",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "pacbio",
                "revio",
                "sequel",
                "hifi",
                "pacbio hifi",
                "long-read sequencing",
            ],
        },
        {
            "canonical_name": "PromethION / P2 Solo",
            "vendor": "Oxford Nanopore",
            "parent_company": "Oxford Nanopore",
            "ticker": "ONT",
            "category": "Long-Read Sequencing",
            "gliner_label": "dna sequencer",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "nanopore",
                "ont",
                "promethion",
                "minion",
                "p2solo",
                "p2 solo",
                "nanopore sequencing",
            ],
        },
        {
            "canonical_name": "DNBSEQ-T7",
            "vendor": "MGI",
            "parent_company": "MGI Tech",
            "ticker": "Private (China)",
            "category": "NGS Sequencing",
            "gliner_label": "dna sequencer",
            "revenue_model": "Razor-Blade",
            "aliases": ["mgi", "dnbseq", "bgi", "stereoseq"],
        },
        {
            "canonical_name": "AVITI",
            "vendor": "Element Biosciences",
            "parent_company": "Element Biosciences",
            "ticker": "Private",
            "category": "NGS Sequencing",
            "gliner_label": "dna sequencer",
            "revenue_model": "Razor-Blade",
            "aliases": ["element", "aviti", "element biosciences"],
        },
        # --- SINGLE-CELL & SPATIAL OMICS ---
        {
            "canonical_name": "Chromium Controller",
            "vendor": "10x Genomics",
            "parent_company": "10x Genomics",
            "ticker": "TXG",
            "category": "Single-Cell",
            "gliner_label": "single cell controller",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "10x",
                "chromium",
                "10x genomics",
                "chromium controller",
                "single-cell rnaseq",
                "scrna-seq",
            ],
        },
        {
            "canonical_name": "Visium / Xenium",
            "vendor": "10x Genomics",
            "parent_company": "10x Genomics",
            "ticker": "TXG",
            "category": "Spatial Omics",
            "gliner_label": "microscope",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "visium",
                "xenium",
                "10x visium",
                "10x xenium",
                "spatial transcriptomics",
            ],
        },
        {
            "canonical_name": "MERSCOPE",
            "vendor": "Vizgen",
            "parent_company": "Vizgen",
            "ticker": "Private",
            "category": "Spatial Omics",
            "gliner_label": "microscope",
            "revenue_model": "Razor-Blade",
            "aliases": ["merscope", "merfish", "vizgen"],
        },
        {
            "canonical_name": "PhenoCycler",
            "vendor": "Akoya Biosciences",
            "parent_company": "Akoya Biosciences",
            "ticker": "AKYA",
            "category": "Spatial Omics",
            "gliner_label": "microscope",
            "revenue_model": "Razor-Blade",
            "aliases": ["phenocycler", "codex", "opal", "akoya"],
        },
        {
            "canonical_name": "CosMx / GeoMx",
            "vendor": "Standard BioTools",
            "parent_company": "Standard BioTools",
            "ticker": "LAB",
            "category": "Spatial Omics",
            "gliner_label": "single cell controller",
            "revenue_model": "Razor-Blade",
            "aliases": ["cosmx", "geomx", "nanostring", "standard biotools"],
        },
        # --- FLOW CYTOMETRY & CELL SORTING ---
        {
            "canonical_name": "FACSAria / LSRFortessa",
            "vendor": "BD Biosciences",
            "parent_company": "BD",
            "ticker": "BDX",
            "category": "Flow Cytometry",
            "gliner_label": "cell sorter",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "bd facs",
                "facsaria",
                "lsrfortessa",
                "fortessa",
                "bd rhapsody",
                "flow cytometer",
                "facs",
            ],
        },
        {
            "canonical_name": "CytoFLEX",
            "vendor": "Beckman Coulter",
            "parent_company": "Danaher",
            "ticker": "DHR",
            "category": "Flow Cytometry",
            "gliner_label": "flow cytometer",
            "revenue_model": "Razor-Blade",
            "aliases": ["cytoflex", "beckman coulter", "beckman"],
        },
        {
            "canonical_name": "Aurora",
            "vendor": "Cytek",
            "parent_company": "Cytek",
            "ticker": "CTKB",
            "category": "Flow Cytometry",
            "gliner_label": "flow cytometer",
            "revenue_model": "Hybrid",
            "aliases": ["cytek", "aurora", "full spectrum"],
        },
        {
            "canonical_name": "ID7000",
            "vendor": "Sony Biotechnology",
            "parent_company": "Sony",
            "ticker": "Private (Sub)",
            "category": "Flow Cytometry",
            "gliner_label": "flow cytometer",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "sony",
                "id7000",
                "sony id7000",
                "spectral cell analyzer",
            ],
        },
        # --- MASS SPECTROMETRY & PROTEOMICS ---
        {
            "canonical_name": "Orbitrap / Q Exactive",
            "vendor": "Thermo Fisher",
            "parent_company": "Thermo Fisher",
            "ticker": "TMO",
            "category": "Mass Spectrometry",
            "gliner_label": "mass spectrometer",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "orbitrap",
                "thermo",
                "q exactive",
                "fusion lumos",
                "thermo fisher",
                "mass spectrometry",
                "lc-ms",
            ],
        },
        {
            "canonical_name": "timsTOF / timsTOF fleX",
            "vendor": "Bruker",
            "parent_company": "Bruker",
            "ticker": "BRKR",
            "category": "Mass Spectrometry & Imaging",
            "gliner_label": "mass spectrometer",
            "revenue_model": "Hardware/Service",
            "aliases": [
                "bruker",
                "timstof",
                "timstof flex",
                "maldi",
                "fticr",
                "maldi-2",
                "ultraflextreme",
                "rapiflex",
            ],
        },
        {
            "canonical_name": "Shimadzu iMScope",
            "vendor": "Shimadzu",
            "parent_company": "Shimadzu",
            "ticker": "Private (Japan)",
            "category": "Imaging Mass Spectrometry",
            "gliner_label": "mass spectrometer",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "imscope",
                "shimadzu",
                "imscope trio",
                "imscope qt",
                "maldi imaging",
            ],
        },
        {
            "canonical_name": "Waters SYNAPT / MALDI",
            "vendor": "Waters",
            "parent_company": "Waters",
            "ticker": "WAT",
            "category": "Mass Spectrometry",
            "gliner_label": "mass spectrometer",
            "revenue_model": "Razor-Blade",
            "aliases": ["waters", "synapt", "g2-si", "hdms", "maldi synapt"],
        },
        {
            "canonical_name": "MIBI / Multiplexed Ion Beam Imaging",
            "vendor": "Standard BioTools",
            "parent_company": "Standard BioTools",
            "ticker": "LAB",
            "category": "Spatial Proteomics",
            "gliner_label": "mass spectrometer",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "mibi",
                "multiplexed ion beam imaging",
                "fluidigm mibi",
                "standard biotools mibi",
            ],
        },
        # --- ADVANCED IMAGING & MICROSCOPY ---
        {
            "canonical_name": "SP8 / Stellaris",
            "vendor": "Leica",
            "parent_company": "Danaher",
            "ticker": "DHR",
            "category": "Microscopy",
            "gliner_label": "microscope",
            "revenue_model": "Hardware",
            "aliases": [
                "leica",
                "sp8",
                "stellaris",
                "leica microsystems",
                "confocal",
            ],
        },
        {
            "canonical_name": "LSM / Axio",
            "vendor": "Zeiss",
            "parent_company": "Carl Zeiss",
            "ticker": "Private",
            "category": "Microscopy",
            "gliner_label": "microscope",
            "revenue_model": "Hardware",
            "aliases": ["zeiss", "lsm", "axio", "confocal"],
        },
        {
            "canonical_name": "Ti-E / Eclipse",
            "vendor": "Nikon",
            "parent_company": "Nikon",
            "ticker": "Private",
            "category": "Microscopy",
            "gliner_label": "microscope",
            "revenue_model": "Hardware",
            "aliases": ["nikon", "ti-e", "eclipse", "nikon instruments"],
        },
        {
            "canonical_name": "Revolve Microscope",
            "vendor": "Echo",
            "parent_company": "Echo",
            "ticker": "Private",
            "category": "Microscopy",
            "gliner_label": "microscope",
            "revenue_model": "Hardware",
            "aliases": ["revolve", "echo revolve", "rvl2", "widefield microscope"],
        },
        # --- MICROSCOPY SUB-COMPONENTS & OPTICS ---
        {
            "canonical_name": "Mai Tai / Spectra-Physics",
            "vendor": "Spectra-Physics",
            "parent_company": "MKS Instruments",
            "ticker": "MKSI",
            "category": "Microscopy Laser",
            "gliner_label": "electrophysiology equipment",
            "revenue_model": "Hardware",
            "aliases": [
                "spectra-physics",
                "spectraphysics",
                "mai tai",
                "titanium sapphire laser",
                "ultrafast laser",
            ],
        },
        {
            "canonical_name": "ThorLabs Optical Components",
            "vendor": "ThorLabs",
            "parent_company": "ThorLabs",
            "ticker": "Private",
            "category": "Optical Components",
            "gliner_label": "microscope",
            "revenue_model": "Hardware",
            "aliases": ["thorlabs", "thor labs", "detector", "photodiode"],
        },
        {
            "canonical_name": "Physik Instrumente (PI)",
            "vendor": "Physik Instrumente",
            "parent_company": "Physik Instrumente",
            "ticker": "Private",
            "category": "Precision Motion",
            "gliner_label": "microscope",
            "revenue_model": "Hardware",
            "aliases": [
                "physik instrumente",
                "piezo lens holder",
                "piezo stage",
                "pi",
            ],
        },
        {
            "canonical_name": "Galvo / Resonance Scanners",
            "vendor": "Cambridge Tech / Scanlab",
            "parent_company": "Various",
            "ticker": "Various",
            "category": "Optical Scanning",
            "gliner_label": "microscope",
            "revenue_model": "Hardware",
            "aliases": [
                "galvo-mirror",
                "resonance scanner",
                "galvanometer scanner",
                "scan head",
            ],
        },
        {
            "canonical_name": "Custom / Academic Rig",
            "vendor": "Academic / Custom",
            "parent_company": "N/A",
            "ticker": "N/A",
            "category": "Custom Microscopy",
            "gliner_label": "microscope",
            "revenue_model": "N/A",
            "aliases": [
                "custom built",
                "independent neuroscience services",
                "home-built",
                "custom microscope",
            ],
        },
        # --- NEUROTECH & ELECTROPHYSIOLOGY ---
        {
            "canonical_name": "Cerebus / Utah Array",
            "vendor": "Blackrock Neurotech",
            "parent_company": "Blackrock",
            "ticker": "Private",
            "category": "Neurotech",
            "gliner_label": "electrophysiology equipment",
            "revenue_model": "Hardware",
            "aliases": [
                "blackrock",
                "cerebus",
                "utah array",
                "neuropixels",
                "multielectrode array",
            ],
        },
        {
            "canonical_name": "EyeLink 1000",
            "vendor": "SR Research",
            "parent_company": "SR Research",
            "ticker": "Private",
            "category": "Eye Tracking",
            "gliner_label": "electrophysiology equipment",
            "revenue_model": "Hardware",
            "aliases": ["eyelink", "sr research", "eye-link", "eye tracker"],
        },
        # --- QC, CHROMATOGRAPHY & SAMPLE PREP ---
        {
            "canonical_name": "TapeStation / ScreenTape",
            "vendor": "Agilent",
            "parent_company": "Agilent",
            "ticker": "A",
            "category": "Electrophoresis / QC",
            "gliner_label": "chromatography system",
            "revenue_model": "Razor-Blade",
            "aliases": [
                "tapestation",
                "screentape",
                "agilent tapestation",
                "genomic dna screentape",
            ],
        },
        {
            "canonical_name": "MACS Cell Separation System",
            "vendor": "Miltenyi Biotec",
            "parent_company": "Miltenyi Biotec",
            "ticker": "Private",
            "category": "Cell Separation",
            "gliner_label": "single cell isolation system",
            "revenue_model": "Razor-Blade",
            "aliases": ["macs", "miltenyi", "macs system", "macs separator"],
        },
        {
            "canonical_name": "GelDoc / ChemiDoc",
            "vendor": "Bio-Rad",
            "parent_company": "Bio-Rad",
            "ticker": "Private",
            "category": "Imaging",
            "gliner_label": "microscope",
            "revenue_model": "Hardware/Consumables",
            "aliases": ["geldoc", "chemidoc", "bio-rad geldoc", "imaging system"],
        },
        {
            "canonical_name": "Bioruptor",
            "vendor": "Diagenode",
            "parent_company": "Diagenode",
            "ticker": "Private",
            "category": "Sample Prep",
            "gliner_label": "single cell isolation system",
            "revenue_model": "Hardware",
            "aliases": ["bioruptor", "diagenode", "sonicator"],
        },
        {
            "canonical_name": "Easy-nLC",
            "vendor": "Thermo Fisher",
            "parent_company": "Thermo Fisher",
            "ticker": "TMO",
            "category": "Chromatography",
            "gliner_label": "chromatography system",
            "revenue_model": "Razor-Blade",
            "aliases": ["easy-nlc", "nano lc", "hplc system"],
        },
        {
            "canonical_name": "FAIMS Pro",
            "vendor": "Thermo Fisher",
            "parent_company": "Thermo Fisher",
            "ticker": "TMO",
            "category": "Mass Spectrometry",
            "gliner_label": "mass spectrometer",
            "revenue_model": "Hardware Add-on",
            "aliases": ["faims", "faims pro", "faims pro interface"],
        },
        # 1. Agilent Bioanalyzer (Missed in logs: "agilent 2100 bioanalyzer")
        {
            "canonical_name": "2100 Bioanalyzer",
            "vendor": "Agilent",
            "parent_company": "Agilent",
            "ticker": "A",
            "category": "Electrophoresis / QC",
            "gliner_label": "chromatography system",
            "revenue_model": "Razor-Blade",
            "aliases": ["bioanalyzer", "agilent 2100", "2100 bioanalyzer", "agilent bioanalyzer"],
        },
        # 2. Stereotaxic Frame (Missed in logs: "stereotaxic apparatus")
        {
            "canonical_name": "Stereotaxic Frame",
            "vendor": "Kopf / Stoelting",
            "parent_company": "Custom / Academic",
            "ticker": "Private",
            "category": "Neurotech Hardware",
            "gliner_label": "electrophysiology equipment",
            "revenue_model": "Hardware",
            "aliases": ["stereotaxic apparatus", "stereotaxic frame", "stereotaxic instrument"],
        },
        # 3. Mass Cytometry (Missed in logs: "mass cytometry")
        {
            "canonical_name": "CyTOF / Helios",
            "vendor": "Standard BioTools",
            "parent_company": "Standard BioTools",
            "ticker": "LAB",
            "category": "Mass Cytometry",
            "gliner_label": "mass spectrometer",
            "revenue_model": "Razor-Blade",
            "aliases": ["cytof", "helios", "mass cytometer", "cytof time-of-flight"],
        }
    ]

    df_registry = pd.DataFrame(registry_data)

    # 1. Dynamically extract all unique non-null gliner_labels
    stage2_target_labels = (
        df_registry["gliner_label"].dropna().unique().tolist()
    )

    # 2. Convert aliases array into JSON strings for CSV compatibility
    df_registry["aliases"] = df_registry["aliases"].apply(json.dumps)

    # 3. Save machine registry CSV
    df_registry.to_csv("../data/machine_registry.csv", index=False)

    # 4. Save Stage 2 extraction target labels JSON
    with open("../data/stage2_labels.json", "w") as f:
        json.dump(stage2_target_labels, f, indent=2)

    print("=" * 70)
    print("REGISTRY GENERATION COMPLETE")
    print("=" * 70)
    print(
        f"• Saved {len(df_registry)} hardware entries to 'machine_registry.csv'"
    )
    print(
        f"• Derived {len(stage2_target_labels)} GLiNER labels to 'stage2_labels.json'"
    )
    print("\nStage 2 GLiNER Target Labels:")
    for label in stage2_target_labels:
        print(f"  - {label}")


if __name__ == "__main__":
    create_registry()